# Task 9 — Feature Engineering
## Step 3: Encoding Categorical Variables

**Goal:** Convert all categorical columns into numerical representations
so they can be used by machine learning algorithms.

| Column | Type | Strategy | Reason |
|--------|------|----------|---------|
| `Sex` | Binary | Label Encoding | Only 2 values (male/female) |
| `Embarked` | Nominal | One-Hot Encoding | 3 unordered categories |
| `Pclass` | Ordinal | Already numeric | No change needed |

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

sns.set_theme(style='whitegrid')

df = pd.read_csv('../data/cleaned_dataset.csv')
print(f'Shape: {df.shape}')
df.head()

Shape: (1309, 8)

    Age     Fare  Sex  sibsp  Parch  Pclass  Embarked  Survived
0  22.0   7.2500    0      1      0       3       2.0         0
1  38.0  71.2833    1      1      0       1       0.0         1
2  26.0   7.9250    1      0      0       3       2.0         1
3  35.0  53.1000    1      1      0       1       2.0         1
4  35.0   8.0500    0      0      0       3       2.0         0

### 3.1 Identify Categorical Columns

In [3]:
# Check for both 'object' (strings) and 'category' dtypes
cat_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()

print(f'Categorical columns found: {len(cat_cols)}')
print(f'List: {cat_cols}\n')

if len(cat_cols) > 0:
    for col in cat_cols:
        # Standard spaces used for indentation here!
        print(f'{col}: {df[col].unique()}')
else:
    print("No categorical columns left! Everything is numeric.")

Categorical columns found: 0
List: []

No categorical columns left! Everything is numeric.

### 3.2 Verify All Columns are Numeric

In [4]:
print('Data types after encoding:')
print(df.dtypes)
print(f'\nAny object columns remaining: {df.select_dtypes(include="object").shape[1]}')

Data types after encoding:
Age         float64
Fare        float64
Sex           int64
sibsp         int64
Parch         int64
Pclass        int64
Embarked    float64
Survived      int64
dtype: object

Any object columns remaining: 0

### 3.5 Final Shape & Preview

In [5]:
print(f'Shape after encoding: {df.shape}')
df.head()

Shape after encoding: (1309, 8)

    Age     Fare  Sex  sibsp  Parch  Pclass  Embarked  Survived
0  22.0   7.2500    0      1      0       3       2.0         0
1  38.0  71.2833    1      1      0       1       0.0         1
2  26.0   7.9250    1      0      0       3       2.0         1
3  35.0  53.1000    1      1      0       1       2.0         1
4  35.0   8.0500    0      0      0       3       2.0         0